#pragma once

#if PICO_RP2350
#define PSRAM_CS1_GPIO_RP2350A 19
#define PSRAM_CS1_GPIO_RP2350B 47
#endif

#define PICO_FLASH_SIZE_BYTES 16777216
#define SDCARD_SPI_BUS spi0
#define SDCARD_PIN_SPI0_CS 5
#define SDCARD_PIN_SPI0_SCK 2
#define SDCARD_PIN_SPI0_MOSI 3
#define SDCARD_PIN_SPI0_MISO 4
#define PS2KBD_GPIO_FIRST 0
#define NES_GPIO_CLK 14
#define NES_GPIO_LAT 15
#define NES_GPIO_DATA 16
#define VGA_BASE_PIN 6
#define HDMI_BASE_PIN 6
#define TFT_CS_PIN 6
#define TFT_RST_PIN 8
#define TFT_LED_PIN 9
#define TFT_DC_PIN 10
#define TFT_DATA_PIN 12
#define TFT_CLK_PIN 13
#define AUDIO_PWM_PIN 26
#define AUDIO_DATA_PIN 26
#define AUDIO_CLOCK_PIN 27
#define PSRAM_PIN_CS 18
#define PSRAM_PIN_SCK 19
#define PSRAM_PIN_MOSI 20
#define PSRAM_PIN_MISO 21
#define WONDERSWAN_LEGACY_SPI_PSRAM 1
#define PICO_DEFAULT_LED_PIN 25
