#pragma once
#define RASPBERRYPI_RP2350_PIZERO
#define PICO_RP2350A 0
#define PICO_PIO_USE_GPIO_BASE 1
#define PICO_FLASH_SIZE_BYTES 16777216
#ifndef PICO_DEFAULT_UART
#define PICO_DEFAULT_UART 0
#endif
#ifndef PICO_DEFAULT_UART_TX_PIN
#define PICO_DEFAULT_UART_TX_PIN 0
#endif
#ifndef PICO_DEFAULT_UART_RX_PIN
#define PICO_DEFAULT_UART_RX_PIN 1
#endif
#ifndef PICO_DEFAULT_LED_PIN
#define PICO_DEFAULT_LED_PIN 25
#endif
#define ZERO 1
#define PSRAM_CS1_GPIO_RP2350A 47
#define PSRAM_CS1_GPIO_RP2350B 47
#define PSRAM_PIN_CS 0
#define PSRAM_PIN_SCK 0
#define PSRAM_PIN_MOSI 0
#define PSRAM_PIN_MISO 0
#define SDCARD_SPI_BUS spi1
#define SDCARD_PIN_SPI0_SCK 30
#define SDCARD_PIN_SPI0_MOSI 31
#define SDCARD_PIN_SPI0_MISO 40
#define SDCARD_PIN_SPI0_CS 43
#define PS2KBD_GPIO_FIRST 2
#define NES_GPIO_CLK 4
#define NES_GPIO_LAT 5
#define NES_GPIO_DATA 7
#define VGA_BASE_PIN 32
#define HDMI_BASE_PIN 32
#define AUDIO_PWM_PIN 10
#define AUDIO_DATA_PIN 10
#define AUDIO_CLOCK_PIN 11
